import {
  Injectable,
  BadRequestException,
  NotFoundException,
  ForbiddenException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import {
  AppraisalObjectiveRatingDto,
  FeedbackQuestionDto,
  AppraisalPipDto,
  FillAppraisalDto,
  GetAppraisalsDto,
  GoalsAndAchievementDto,
  SignatureDto,
} from './dto/apppraisal.dto';
import { Prisma, Role, User } from '@prisma/client';
import { bad } from 'src/utils/error.utils';
import { EventEmitter2 } from '@nestjs/event-emitter';
import {
  AppraisalCreatedEvent,
  AppraisalSubmittedEvent,
  AppraisalReviewedEvent,
} from 'src/events/appraisal.event';

@Injectable()
export class AppraisalService {
  private readonly logger = new Logger(AppraisalService.name);
  constructor(
    private readonly prisma: PrismaService,
    private eventEmitter: EventEmitter2,
  ) { }

  // Manager sends appraisals to department (makes them available for filling)
  async sendAppraisalToTeam(
    userId: string,
    appraisalId: string,
    data: GetAppraisalsDto,
  ) {
    const { departmentId, quarter, year } = data;

    //Fetch the template appraisal for this department + period
    const template = await this.prisma.appraisal.findFirst({
      where: {
        departmentId,
        quarter,
        year,
        isTemplate: true,
      },
      include: {
        kpi: {
          include: {
            categories: {
              include: { objectives: true },
            },
          },
        },
        appraisalObj: {
          include: {
            kpiCategory: {
              include: {
                objectives: true,
              },
            },
          },
        },
        goalsAndAchievement: true,
        feedback: { include: { questions: true } },
      },
    });

    if (!template)
      throw new BadRequestException('No template found for this department.');

    //Fetch employees in this department
    const employees = await this.prisma.user.findMany({
      where: {
        userRole: { hasSome: ['USER', "TEAM_LEAD"] },
        departments: { some: { id: departmentId } },
      },
    });

    if (employees.length === 0)
      throw new BadRequestException('No employees in this department.');

    const createdAppraisals = [];

    //Loop through department employees
    for (const employee of employees) {
      const existing = await this.prisma.appraisal.findFirst({
        where: { quarter, year, appraisedId: employee.id },
      });
      if (existing) continue; // avoid duplicates

      //Create appraisal for employee
      const employeeAppraisal = await this.prisma.appraisal.create({
        data: {
          quarter,
          year,
          departmentId,
          appraiserId: userId,
          appraisedId: employee.id,
          templateId: template.id,
          status: 'PENDING',
          isTemplate: false,
          autoGenerated: false,
          period: template.period,
          goalsAndAchievement: {
            create: { achievements: [], goals: [] },
          },
          feedback: {
            create: {
              questions: {
                create:
                  template.feedback?.questions.map((q) => ({
                    question: q.question,
                    order: q.order,
                  })) || [],
              },
            },
          },
        },
      });

      //Create employee-specific objective ratings (empty initially)
      for (const kpi of template.kpi) {
        for (const category of kpi.categories) {
          for (const objective of category.objectives) {
            await this.prisma.appraisalObjective.create({
              data: {
                appraisal: { connect: { id: employeeAppraisal.id } },
                objective: { connect: { id: objective.id } },
                kpiCategory: { connect: { id: objective.categoryId } },
              },
            });
          }
        }
      }

      createdAppraisals.push(employeeAppraisal);

      // Emit Event
      this.eventEmitter.emit(
        'appraisal.created',
        new AppraisalCreatedEvent(
          employeeAppraisal.id,
          employeeAppraisal.appraisedId,
          userId,
          [employeeAppraisal.appraisedId],
        ),
      );
    }

    //Return summary
    return {
      success: true,
      message: `Appraisals sent to ${createdAppraisals.length} team member(s).`,
      data: createdAppraisals,
    };
  }

  async saveAppraisalDraft(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
  ) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        departments: { include: { approver: true } },
      },
    });
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: { department: true },
    });
    if (this.userHasRole(user, Role.USER)) {
      if (appraisal.appraisedId !== userId) {
        throw bad('Not authorized to fill this appraisal');
      }
      return this.saveUserDraft(userId, appraisalId, data);
    } else if (this.userHasRole(user, Role.DEPT_MANAGER)) {
      const isManager = this.isManagerOfUser(userId, appraisal.appraisedId);
      if (!isManager) {
        throw bad('You are not authorized to appraise this user');
      }
      if (
        appraisal.status !== 'SUBMITTED' &&
        appraisal.status !== 'MANAGER_DRAFT'
      ) {
        throw bad(
          'Cannot save draft for an appraisal with status: ' +
          appraisal.status +
          '. Appraisal must be submitted by employee first.',
        );
      }
      return this.saveManagerDraft(userId, appraisalId, data);
    } else {
      throw bad('Invalid role for this operation');
    }
  }

  async submitAppraisal(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
    isDraft: boolean = false,
  ) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        departments: { include: { approver: true } },
      },
    });
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: { department: true },
    });
    if (!user.userRole.includes(Role.DEPT_MANAGER)) {
      if (appraisal.appraisedId !== userId) {
        throw bad('Not authorized to fill this appraisal');
      }
      return this.submitUserAppraisal(userId, appraisalId, data, isDraft);
    } else if (user.userRole.includes(Role.DEPT_MANAGER)) {
      const isManager = this.isManagerOfUser(userId, appraisal.appraisedId);
      if (!isManager) {
        throw bad('You are not authorized to appraise this user');
      }
      if (
        appraisal.status !== 'SUBMITTED' &&
        appraisal.status !== 'MANAGER_DRAFT'
      ) {
        throw bad(
          'Cannot appraise an appraisal with status: ' +
          appraisal.status +
          '. Appraisal must be submitted by employee first.',
        );
      }
      return this.appraiseSubmission(userId, appraisalId, data, isDraft);
    } else {
      throw bad('Invalid role for this operation');
    }
  }

  async editAppraisal(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
  ) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        departments: { include: { approver: true } },
      },
    });
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: { department: true },
    });

    if (!appraisal) throw new NotFoundException('Appraisal not found');

    if (!user.userRole.includes(Role.DEPT_MANAGER)) {
      if (appraisal.appraisedId !== userId && appraisal.appraiserId !== userId) {
        throw bad('Not authorized to edit this appraisal');
      }


      // Allow editing if status is DRAFT or SUBMITTED
      if (!['DRAFT', 'SUBMITTED'].includes(appraisal.status)) {
        throw bad(`Cannot edit appraisal with status: ${appraisal.status}`);
      }
      return this.performEdit(userId, appraisalId, data, 'USER');
    } else if (user.userRole.includes(Role.DEPT_MANAGER)) {
      const isManager = this.isManagerOfUser(userId, appraisal.appraisedId);
      if (!isManager) {
        throw bad('You are not authorized to edit this user\'s appraisal');
      }
      // Allow editing if status is APPRAISED or MANAGER_DRAFT
      if (!['APPRAISED', 'MANAGER_DRAFT', 'SUBMITTED'].includes(appraisal.status)) {
        throw bad(`Cannot edit appraisal with status: ${appraisal.status}`);
      }
      return this.performEdit(userId, appraisalId, data, 'DEPT_MANAGER');
    } else {
      throw bad('Invalid role for this operation');
    }
  }

  private async performEdit(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
    role: 'USER' | 'DEPT_MANAGER',
  ) {
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: {
        appraisalObj: { include: { objective: true } },
      },
    });

    const {
      objectiveRatings,
      goalsAndAchievements,
      feedback,
      signatures,
      appraisalPip,
      managerComment,
    } = data;

    await this.prisma.$transaction(async (tx) => {
      // Update Kpi Objective Ratings
      if (objectiveRatings?.length > 0) {
        await this.updateObjectiveRatings(tx, appraisal, objectiveRatings);
      }

      // Update Goals & Achievements
      if (goalsAndAchievements) {
        await this.updateGoalsAndAchievements(
          tx,
          appraisalId,
          goalsAndAchievements,
        );
      }

      // Update Feedback
      if (feedback?.length > 0) {
        await this.updateFeedbackResponses(tx, feedback);
      }
      // Update Signatures (Employee)
      if (signatures) {
        await this.updateSignatures(tx, appraisalId, signatures, 'employee');
      }
      // Update PIP
      if (appraisalPip !== undefined) {
        await this.updateAppraisalPip(tx, appraisalId, appraisalPip);
      }

      if (managerComment !== undefined) {
        await tx.appraisal.update({
          where: { id: appraisalId },
          data: { managerComment, updatedAt: new Date() },
        });
      }

      // Recalculate ratings
      await this.calculateRatingSummary(appraisalId);

      await tx.appraisal.update({
        where: { id: appraisalId },
        data: { updatedAt: new Date() },
      });
    });

    return this.getOneAppraisal(appraisalId);
  }

  private async appraiseSubmission(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
    isDraft: boolean,
  ) {
    const appraisal = await this.validateManagerAppraisal(userId, appraisalId);

    const { objectiveRatings, goalsAndAchievements, managerComment } = data;

    //Update appraisal in transaction
    await this.prisma.$transaction(async (tx) => {
      //Update Kpi Objectives
      if (objectiveRatings?.length > 0) {
        await this.updateObjectiveRatings(tx, appraisal, objectiveRatings);
      }
      //Update Goals & Achievements
      if (goalsAndAchievements) {
        await this.updateGoalsAndAchievements(
          tx,
          appraisalId,
          goalsAndAchievements,
        );
      }

      //Calculate Appraisal Rating Summary
      await this.calculateRatingSummary(appraisalId);

      //Update Appraisal as Appraised
      await tx.appraisal.update({
        where: { id: appraisalId },
        data: {
          status: isDraft ? 'MANAGER_DRAFT' : 'APPRAISED',
          managerComment: managerComment,
          appraisedAt: new Date(),
          updatedAt: new Date(),
        },
      });

      // Update Signatures
      if (data.signatures) {
        await this.updateSignatures(tx, appraisalId, data.signatures, 'manager');
      }
    });

    const updatedAppraisal = await this.getOneAppraisal(appraisalId);

    // Emit Event
    this.eventEmitter.emit(
      'appraisal.reviewed',
      new AppraisalReviewedEvent(
        updatedAppraisal.id,
        updatedAppraisal.appraisedId,
        userId,
        [updatedAppraisal.appraisedId],
      ),
    );

    return updatedAppraisal;
  }

  private async submitUserAppraisal(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
    isDraft: boolean,
  ) {
    const appraisal = await this.validateUserAppraisal(userId, appraisalId);
    const { objectiveRatings, feedback, goalsAndAchievements, signatures, appraisalPip } = data;

    await this.prisma.$transaction(async (tx) => {

      //Update Kpi Objective Ratings
      if (objectiveRatings?.length > 0) {
        await this.updateObjectiveRatings(tx, appraisal, objectiveRatings);
      }

      //Update Goals & Achievements
      if (goalsAndAchievements) {
        await this.updateGoalsAndAchievements(
          tx,
          appraisalId,
          goalsAndAchievements,
        );
      }
      //Update Feedback
      if (feedback?.length > 0) {
        await this.updateFeedbackResponses(tx, feedback);
      }
      //update signatures
      if (signatures) {
        await this.updateSignatures(tx, appraisalId, signatures, 'employee');
      }

      //update Appraisal Pip
      if (appraisalPip?.length > 0) {
        await this.updateAppraisalPip(tx, appraisalId, appraisalPip);
      }

      //Calculate ratings and Update Status
      await this.calculateRatingSummary(appraisalId);

      await tx.appraisal.update({
        where: { id: appraisalId },
        data: {
          status: isDraft ? 'DRAFT' : 'SUBMITTED',
          submittedAt: new Date(),
          updatedAt: new Date(),
        },
      });
    });
    const updatedAppraisal = await this.getOneAppraisal(appraisalId);

    // Emit Event
    this.eventEmitter.emit(
      'appraisal.submitted',
      new AppraisalSubmittedEvent(
        updatedAppraisal.id,
        userId,
        updatedAppraisal.appraiserId,
        [updatedAppraisal.appraiserId],
      ),
    );

    return updatedAppraisal;
  }

  private async saveManagerDraft(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
  ) {
    //Find appraisal and validate manager authorization
    const appraisal = await this.validateManagerAppraisal(userId, appraisalId);

    const { objectiveRatings, goalsAndAchievements, managerComment } = data;

    //Update appraisalin transaction
    await this.prisma.$transaction(async (tx) => {
      //Update Kpi Objectives
      if (objectiveRatings?.length > 0) {
        await this.updateObjectiveRatings(tx, appraisal, objectiveRatings);
      }

      //Update Goals & Achievements
      if (goalsAndAchievements) {
        await this.updateGoalsAndAchievements(
          tx,
          appraisalId,
          goalsAndAchievements,
        );
      }

      //Update Appraisal as Manager draft
      await tx.appraisal.update({
        where: { id: appraisalId },
        data: {
          status: 'MANAGER_DRAFT',
          managerComment: managerComment,
        },
      });
    });

    const updatedAppraisal = await this.getOneAppraisal(appraisalId);

    return updatedAppraisal;
  }

  private async saveUserDraft(
    userId: string,
    appraisalId: string,
    data: FillAppraisalDto,
  ) {
    const appraisal = await this.validateUserAppraisal(userId, appraisalId);

    const { objectiveRatings, goalsAndAchievements, feedback } = data;
    await this.prisma.$transaction(async (tx) => {
      //Update Kpi Objective Ratings
      if (objectiveRatings?.length > 0) {
        await this.updateObjectiveRatings(tx, appraisal, objectiveRatings);
      }
      //Update Goals & Achievements
      if (goalsAndAchievements) {
        await this.updateGoalsAndAchievements(
          tx,
          appraisalId,
          goalsAndAchievements,
        );
      }
      //Update Feedback
      if (feedback?.length > 0) {
        await this.updateFeedbackResponses(tx, feedback);
      }
      //Update Appraisal Status
      await tx.appraisal.update({
        where: { id: appraisalId },
        data: {
          status: 'DRAFT',
          updatedAt: new Date(),
        },
      });
    });
    const updatedAppraisal = await this.getOneAppraisal(appraisalId);
    return updatedAppraisal;
  }

  async getAppraisalForUser(userId: string, filters?: GetAppraisalsDto) {
    // Ensure user roles are loaded
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: { appraisals: { select: { id: true } } },
    });
    if (!user) throw new NotFoundException('User not found');

    const userRoles = user.userRole || [];

    const isAdmin = userRoles.includes(Role.ADMIN);
    const isHR = userRoles.includes(Role.HR);
    const isManager = userRoles.includes(Role.DEPT_MANAGER);
    const isUser = userRoles.includes(Role.USER);
    const where: Prisma.AppraisalWhereInput = {};

    // Optional filters
    if (filters?.quarter) where.quarter = filters.quarter;
    if (filters?.year) where.year = Number(filters.year);
    if (filters?.status) where.status = filters.status;

    // Common include for all queries
    const appraisalInclude = {
      appraisalPip: true,
      managerSignature: {
        include: {
          signature: {
            select: {
              id: true,
              name: true,
              size: true,
              uri: true,
              type: true
            }
          }
        }
      },
      employeeSignature: {
        include: {
          signature: {
            select: {
              id: true,
              name: true,
              size: true,
              uri: true,
              type: true
            }
          }
        }
      },
      appraised: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          role: true,
          eId: true,
        },
      },
      appraiser: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          role: true,
          eId: true,
        },
      },
      department: true,
      kpi: {
        include: {
          categories: {
            include: {
              objectives: {
                include: { appraisalObj: { include: { objective: true, kpiCategory: true } } },
              },
            },
          },
        },
      },
      appraisalObj: {
        include: { appraisal: true, objective: true, kpiCategory: true }
      },
      goalsAndAchievement: true,
      feedback: { include: { questions: true } },
      summary: {
        include: {
          kpiCategory: { select: { id: true, name: true } },
        },
      },
    };

    /**
     * ADMIN or HR → can view all appraisals
     */
    if (isAdmin || isHR) {
      return await this.prisma.appraisal.findMany({
        where,
        include: appraisalInclude,
      });
    }

    /**
     * MANAGER → can view appraisals of their team
     */
    if (isManager) {
      const departments = await this.prisma.department.findMany({
        where: { user: { some: { id: user.id } } },
        select: { id: true },
      });

      const departmentIds = departments.map((d) => d.id);

      return await this.prisma.appraisal.findMany({
        where: {
          ...where,
          departmentId: { in: departmentIds },
          appraiserId: user.id,
        },
        include: appraisalInclude,
      });
    }
    /**
     * USER → can view:
     *  - their own appraisals
     *  - manager’s sent team appraisals (pending)
     */
    if (isUser) {
      const userDepartments = await this.prisma.department.findMany({
        where: { user: { some: { id: user.id } } },
        select: { id: true },
      });

      const departmentIds = userDepartments.map((d) => d.id);

      // Get all appraisal IDs for this user to exclude when needed
      const userAppraisalIds = user.appraisals.map((a) => a.id);

      return await this.prisma.appraisal.findMany({
        where: {
          ...where,
          OR: [
            { appraisedId: user.id },
            {
              departmentId: { in: departmentIds },
              status: 'PENDING',
              appraisedId: null,
            },
          ],
        },
        include: {
          ...appraisalInclude,
          appraisalObj: {
            include: {
              objective: true,
              kpiCategory: true,
            },
          },
        },
      });
    }

    throw new ForbiddenException('Unauthorized role');
  }

  async listAppraisals(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
    });
    if (!user) throw new NotFoundException('User not found');

    const userRoles = user.userRole || [];
    const isAdmin = userRoles.includes(Role.ADMIN) || userRoles.includes(Role.SUPERADMIN);
    const isHR = userRoles.includes(Role.HR);
    const isManager = userRoles.includes(Role.DEPT_MANAGER);

    if (!isAdmin && !isHR && !isManager) {
      throw new ForbiddenException('Strictly for managers, admins and hrs');
    }

    const where: Prisma.AppraisalWhereInput = { isTemplate: false };

    if (isManager && !isAdmin && !isHR) {
      const managedDepartments = await this.prisma.department.findMany({
        where: { user: { some: { id: userId } } },
        select: { id: true },
      });
      const departmentIds = managedDepartments.map((d) => d.id);
      where.departmentId = { in: departmentIds };
    }

    const appraisals = await this.prisma.appraisal.findMany({
      where,
      include: {
        department: true,
        appraised: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            eId: true,
            role: true,
          },
        },
        appraiser: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
          },
        },
        summary: true,
      },
      orderBy: [
        { year: 'desc' },
        { quarter: 'desc' },
        { department: { name: 'asc' } },
      ],
    });

    type AppraisalWithRelations = Prisma.AppraisalGetPayload<{
      include: {
        department: true;
        appraised: {
          select: {
            id: true;
            firstName: true;
            lastName: true;
            email: true;
            eId: true;
            role: true;
          };
        };
        appraiser: {
          select: {
            id: true;
            firstName: true;
            lastName: true;
            email: true;
          };
        };
        summary: true;
      };
    }>;


    // Grouping: Period -> Department -> Appraisals
    const grouped = appraisals.reduce((acc: {
      [period: string]: {
        [departmentName: string]: AppraisalWithRelations[];
      };
    }, appraisal: AppraisalWithRelations) => {
      const period = appraisal.period || `${appraisal.quarter} ${appraisal.year}`;
      const departmentName = appraisal.department?.name || 'Unknown Department';

      if (!acc[period]) {
        acc[period] = {};
      }

      if (!acc[period][departmentName]) {
        acc[period][departmentName] = [];
      }

      acc[period][departmentName].push(appraisal);
      return acc;
    }, {});

    return grouped;
  }

  async getOneAppraisal(id: string) {
    try {
      return await this.prisma.appraisal.findUnique({
        where: { id },
        include: {
          appraised: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              email: true,
              role: true,
              eId: true,
            },
          },
          appraiser: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              email: true,
              role: true,
              eId: true,
            },
          },
          department: true,
          appraisalObj: { include: { objective: true, kpiCategory: true } },
          kpi: {
            include: {
              categories: {
                include: {
                  objectives: {
                    include: { appraisalObj: { include: { objective: true } } },
                  },
                },
              },
            },
          },
          goalsAndAchievement: true,
          feedback: { include: { questions: true } },
          summary: {
            include: {
              kpiCategory: { select: { id: true, name: true } },
            },
          },
          appraisalPip: true,
          employeeSignature: {
            include: {
              signature: {
                select: {
                  id: true,
                  name: true,
                  size: true,
                  uri: true,
                  type: true
                }
              }
            }
          },
          managerSignature: {
            include: {
              signature: {
                select: {
                  id: true,
                  name: true,
                  size: true,
                  uri: true,
                  type: true
                }
              }
            }
          }
        },
      });
    } catch (error) {
      if (
        error instanceof BadRequestException ||
        error instanceof NotFoundException ||
        error instanceof ConflictException
      ) {
        console.log(error);
      }
      throw new BadRequestException(
        'Failed to delete KPI Category: ' + error.message,
      );
    }
  }

  /**
   * Calculate overall rating summary for an appraisal
   * based on its AppraisalObjectives.
   */

  async calculateRatingSummary(appraisalId: string) {
    try {
      // Fetch all KPI categories (both global and departmental) for this appraisal
      const kpi = await this.prisma.kpi.findUnique({
        where: { appraisalId },
        include: {
          categories: {
            include: {
              objectives: true,
            },
          },
        },
      });

      if (!kpi || kpi.categories.length === 0) {
        return { categories: [], overallAverage: null };
      }

      const categorySummaries: {
        categoryId: string;
        categoryName: string;
        averageRating: number | null;
      }[] = [];

      const allRatings: number[] = [];

      // --- Compute per-category averages ---
      for (const category of kpi.categories) {
        const ratings = category.objectives
          .filter((obj) => obj.rating != null)
          .map((obj) => obj.rating as number);

        const avg =
          ratings.length > 0
            ? parseFloat(
              (
                ratings.reduce((sum, r) => sum + r, 0) / ratings.length
              ).toFixed(2),
            )
            : null;

        if (ratings.length > 0) {
          allRatings.push(...ratings);
        }

        categorySummaries.push({
          categoryId: category.id,
          categoryName: category.name,
          averageRating: avg,
        });

        // Persist each category summary
        // await this.prisma.ratingSummary.upsert({
        //     where: {
        //         appraisalId_kpiCategoryId: {
        //             appraisalId,
        //             kpiCategoryId: category.id,
        //         },
        //     },
        //     update: { averageRating: avg },
        //     create: {
        //         appraisalId,
        //         kpiCategoryId: category.id,
        //         averageRating: avg,
        //     },
        // });
      }

      // --- Compute overall average ---
      const overallAverage =
        allRatings.length > 0
          ? parseFloat(
            (
              allRatings.reduce((sum, r) => sum + r, 0) / allRatings.length
            ).toFixed(2),
          )
          : null;

      // Update overall average on the appraisal
      await this.prisma.appraisal.update({
        where: { id: appraisalId },
        data: { averageRating: overallAverage },
      });

      return {
        overallAverage,
        categories: categorySummaries,
      };
    } catch (error) {
      if (
        error instanceof BadRequestException ||
        error instanceof NotFoundException ||
        error instanceof ConflictException
      ) {
        throw error;
      }
      throw new BadRequestException(
        'Failed to calculate rating summary: ' + error.message,
      );
    }
  }

  /////////////////////////////////////////////// HELPER METHODS ///////////////////////////////////////////

  private async updateObjectiveRatings(
    tx: Prisma.TransactionClient,
    appraisal: Prisma.AppraisalGetPayload<{ include: { appraisalObj: true } }>,
    objectiveRatings: AppraisalObjectiveRatingDto[],
  ) {
    const validObjectiveIds = new Set(
      appraisal.appraisalObj.map((obj) => obj.id),
    );

    const updates = objectiveRatings
      .filter((obj) => validObjectiveIds.has(obj.appraisalObjId))
      .map((obj) => {
        return tx.appraisalObjective.update({
          where: { id: obj.appraisalObjId },
          data: {
            rating: obj.rating ?? null,
            comment: obj.comment ?? null,
          },
        });
      });

    await Promise.all(updates);
  }

  private async updateGoalsAndAchievements(
    tx: Prisma.TransactionClient,
    appraisalId: string,
    goalsAndAchievements: GoalsAndAchievementDto,
  ) {
    await tx.goalsAndAchievement.updateMany({
      where: { appraisalId },
      data: {
        goals: goalsAndAchievements.goals ?? [],
        achievements: goalsAndAchievements.achievements ?? [],
      },
    });
  }

  private async updateFeedbackResponses(
    tx: Prisma.TransactionClient,
    feedback: FeedbackQuestionDto[],
  ) {
    const updates = feedback.map((item) =>
      tx.feedbackQuestion.update({
        where: { id: item.questionId },
        data: { response: item.response },
      }),
    );

    await Promise.all(updates);
  }

  private async updateSignatures(
    tx: Prisma.TransactionClient,
    appraisalId: string,
    signatures: SignatureDto,
    type: 'employee' | 'manager',
  ) {
    const signatureId =
      type === 'employee'
        ? signatures.employeeSignature
        : signatures.managerSignature;
    const date =
      type === 'employee' ? signatures.employeeDate : signatures.managerDate;

    if (!signatureId) return;

    const where =
      type === 'employee'
        ? { employeeSignatureId: appraisalId }
        : { managerSignatureId: appraisalId };

    await tx.appraisalSignatures.upsert({
      where,
      update: {
        signature: { connect: { id: signatureId } },
        date: date ? new Date(date) : new Date(),
      },
      create: {
        signature: { connect: { id: signatureId } },
        date: date ? new Date(date) : new Date(),
        ...(type === 'employee'
          ? { employeeSignature: { connect: { id: appraisalId } } }
          : { managerSignature: { connect: { id: appraisalId } } }),
      },
    });
  }

  private async updateAppraisalPip(
    tx: Prisma.TransactionClient,
    appraisalId: string,
    appraisalPip: AppraisalPipDto[],
  ) {
    // For simplicity, we delete and recreate PIPs to avoid complex ID matching
    // If PIPs have IDs we should ideally upsert, but the DTO doesn't have them yet.
    await tx.appraisalPip.deleteMany({
      where: { appraisalId },
    });

    if (appraisalPip?.length > 0) {
      await tx.appraisalPip.createMany({
        data: appraisalPip.map((pip) => ({
          title: pip.title,
          description: pip.description,
          appraisalId,
          employeeComment: pip.employeeComment,
          managerComment: pip.managerComment,
          status: pip.status,
        })),
      });
    }
  }

  async findAppraisalFeedbackQuestion(appraisalId: string) {
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: { feedback: true },
    });
    return this.prisma.feedbackQuestion.findMany({
      where: { feedbackId: appraisal.feedback.id },
    });
  }

  async getAppraisalRatingSummary(appraisalId: string) {
    return this.prisma.ratingSummary.findMany({
      where: { appraisalId },
      include: { kpiCategory: true },
    });
  }

  private async validateUserAppraisal(userId: string, appraisalId: string) {
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: {
        appraised: { include: { departments: true } },
        appraisalObj: { include: { objective: true } },
        goalsAndAchievement: true,
      },
    });
    if (!appraisal) {
      throw bad('Appraisal Not Found');
    }

    if (appraisal.appraisedId !== userId) {
      throw new ForbiddenException(
        'You are not authorized to access this appraisal',
      );
    }

    //Validate appraisal status
    // if (['SUBMITTED', 'APPRAISED'].includes(appraisal.status)) {
    //   throw bad('This appraisal can no longer be modified');
    // }
    return appraisal;
  }

  private async validateManagerAppraisal(userId: string, appraisalId: string) {
    const appraisal = await this.prisma.appraisal.findUnique({
      where: { id: appraisalId },
      include: {
        appraised: { include: { departments: true } },
        appraisalObj: { include: { objective: true } },
        goalsAndAchievement: true,
      },
    });
    if (!appraisal) {
      throw bad('Appraisal Not Found');
    }

    //Check if manager is authorized to appraise this appraisal
    const isAuthorized = await this.isManagerOfUser(
      userId,
      appraisal.appraisedId,
    );
    if (!isAuthorized) {
      throw bad('You are not authorized to appraise this user');
    }

    //Validate appraisal status - only SUBMITTED or MANAGER_DRAFT appraisals can be appraised
    if (!['SUBMITTED', 'MANAGER_DRAFT'].includes(appraisal.status)) {
      throw bad(
        `Cannot appraise an appraisal with status: ${appraisal.status}. ` +
        'Appraisal must be submitted by employee first.',
      );
    }
    return appraisal;
  }

  private async isManagerOfUser(userId: string, appraisedId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: { departments: { include: { approver: true } } },
    });
    if (this.userHasRole(user, Role.DEPT_MANAGER)) {
      //Check if appraised user is in any of the manager's departments
      const managedDeptIds = user.departments.map((dept) => dept.id);
      const appraisedUser = await this.prisma.user.findUnique({
        where: { id: appraisedId },
        include: { departments: true },
      });
      const appraisedDeptIds = appraisedUser.departments.map((dept) => dept.id);
      const commonDepts = managedDeptIds.filter((id) =>
        appraisedDeptIds.includes(id),
      );
      return commonDepts.length > 0;
    }
  }

  private userHasRole(userObj: User, role: Role) {
    if (!userObj) return false;
    // userObj.userRole may be an array of Role or a single Role string
    const roles = (userObj.userRole ?? userObj.role)
    if (Array.isArray(roles)) return roles.includes(role);
    return roles === role;
  }
}
