import { BadRequestException, ConflictException, Controller, Logger, NotFoundException, Post } from "@nestjs/common";
import { PrismaService } from "src/prisma/prisma.service";
import { DEFAULT_FEEDBACK_QUESTIONS } from "src/constants/kpi-components";

@Controller('appraisal-scheduler')
export class AppraisalSchedulerController {
  private readonly logger = new Logger(AppraisalSchedulerController.name);

  constructor(private readonly prisma: PrismaService) {}

@Post('generate')
async generateQuarterlyAppraisals() {
  this.logger.log('Manually starting quarterly appraisal template generation...');

  const currentDate = new Date();
  const quarter = this.getCurrentQuarter(currentDate);
  const year = currentDate.getFullYear();
  const period = `Quarter ${quarter} ${year}`;

  // Initialize summary counters
  const summary = {
    departmentsChecked: 0,
    skippedNoManager: 0,
    skippedNoKPI: 0,
    alreadyExisting: 0,
    newTemplates: 0,
  };

  try {
    // Fetch all active departments with their active managers
    const departments = await this.prisma.department.findMany({
      where: { status: 'ACTIVE' },
      include: {
        approver: {
          where: { 
            role: 'DEPT_MANAGER',
            user: { status: 'ACTIVE' }
          },
          include: { user: true }
        }
      }
    });

    const appraisalsToCreate = [];

    for (const department of departments) {
      summary.departmentsChecked++;

      // Ensure department has an active manager
      if (!department.approver || department.approver.length === 0) {
        this.logger.warn(`No active department manager found for department ${department.name}. Skipping.`);
        summary.skippedNoManager++;
        continue;
      }

      const manager = department.approver[0];

      // Check if appraisal template already exists for this quarter/year
      const existing = await this.prisma.appraisal.findFirst({
        where: {
          quarter: `${quarter}`,
          year,
          departmentId: department.id,
          appraisedId: null,
          isTemplate: true
        }
      });

      if (existing) {
        this.logger.log(`Appraisal template already exists for department ${department.name} (${period}). Skipping.`);
        summary.alreadyExisting++;
        continue;
      }

      // Get approved KPI categories (global + department)
      const globalCategories = await this.prisma.kpiCategory.findMany({
        where: { isGlobal: true, isApproved: true },
        include: { objectives: true }
      });

      const departmentCategories = await this.prisma.kpiCategory.findMany({
        where: { 
          departmentId: department.id,
          isGlobal: false,
          isApproved: true
        },
        include: { objectives: true }
      });

      const allCategories = [...globalCategories, ...departmentCategories];

      if (allCategories.length === 0) {
        this.logger.warn(`No KPI categories found for department ${department.name}. Skipping.`);
        summary.skippedNoKPI++;
        continue;
      }

      // Add to create list
      appraisalsToCreate.push({
        quarter: `${quarter}`,
        year,
        period,
        appraiserId: manager.userId,
        appraisedId: null,
        status: 'GENERATED',
        autoGenerated: true,
        departmentId: department.id,
        isTemplate: true
      });
    }

    // Create appraisal templates in a transaction
    if (appraisalsToCreate.length > 0) {
      const created = await this.prisma.$transaction(
        appraisalsToCreate.map(data => this.prisma.appraisal.create({ data }))
      );

      summary.newTemplates = created.length;

      this.logger.log(`✅ Successfully created ${created.length} appraisal templates for ${period}.`);

      // Initialize KPI, goals, and feedback for each template
      await this.initializeAppraisalData(created);
    } else {
      this.logger.log(`ℹ️ No new appraisal templates to create for ${period}.`);
    }

    // Final return
    return {
      success: true,
      message:
        summary.newTemplates > 0
          ? `Created ${summary.newTemplates} appraisal templates for ${period}`
          : `No new appraisal templates created for ${period}`,
      period,
      summary
    };

  } catch (error) {
    this.logger.error('❌ Failed to generate quarterly appraisal templates:', error);
    throw new BadRequestException('Failed to generate quarterly appraisal templates: ' + error.message);
  }
}


  /////////////////////////////////// HELPER METHODS ///////////////////////////////////

  private getCurrentQuarter(date: Date): number {
    const month = date.getMonth() + 1;
    return Math.ceil(month / 3);
  }

  private async initializeAppraisalData(appraisals: any[]) {
    for (const appraisal of appraisals) {
      try {
        // Get global KPIs for this appraisal
        const globalCategories = await this.prisma.kpiCategory.findMany({
          where: { 
            isGlobal: true,
            isApproved: true 
          },
          include: { objectives: true }
        });

        // Get department-specific KPIs for this appraisal's department
        const departmentCategories = await this.prisma.kpiCategory.findMany({
          where: { 
            departmentId: appraisal.departmentId,
            isGlobal: false,
            isApproved: true
          },
          include: { objectives: true }
        });

        // Combine all categories
        const allCategories = [...globalCategories, ...departmentCategories];

        if (allCategories.length === 0) {
          this.logger.warn(`No KPI categories found for appraisal template ${appraisal.id}. Skipping KPI initialization.`);
          continue;
        }

        // Create KPI structure with existing categories
        await this.prisma.kpi.create({
          data: {
            appraisalId: appraisal.id,
            categories: {
              create: allCategories.map(category => ({
                name: category.name,
                type: category.type,
                isGlobal: category.isGlobal,
                departmentId: category.departmentId,
                isApproved: true,
                objectives: {
                  create: category.objectives.map(obj => ({
                    name: obj.name,
                    rating: null,
                    comment: null
                  }))
                }
              }))
            }
          }
        });

        // Create empty goals and achievements structure
        await this.prisma.goalsAndAchievement.create({
          data: {
            appraisalId: appraisal.id,
            achievements: [],
            goals: [],
          },
        });

        // Create empty feedback structure
        await this.prisma.feedback.create({
          data: {
            appraisalId: appraisal.id,
            questions: {
              create: DEFAULT_FEEDBACK_QUESTIONS.map(question => ({
                question: typeof question === 'string' ? question : question.question,
                response: null
              }))
            }
          }
        });

        this.logger.log(`Initialized KPI, Goals & Achievement, and Feedback data for appraisal template ID: ${appraisal.id}`);
      } catch (error) {
        this.logger.error(`Failed to initialize data for appraisal template ${appraisal.id}:`, error);
        continue;
      }
    }
  }
}