import { BadRequestException, ConflictException, Injectable, Logger, NotFoundException } from "@nestjs/common";
import { Cron, CronExpression } from "@nestjs/schedule";
import { PrismaService } from "src/prisma/prisma.service";
import { DEFAULT_FEEDBACK_QUESTIONS } from "src/constants/kpi-components";

@Injectable()
export class AppraisalSchedulerService {
    private readonly logger = new Logger(AppraisalSchedulerService.name);

    constructor(private readonly prisma: PrismaService) {}

    // @Cron(CronExpression.EVERY_QUARTER)
    async generateQuaterlyAppraisals(userId: string, data: { quarter: string, year: number }) {
        this.logger.log('Starting quarterly appraisal generation...');

        // const currentDate = new Date();
        // const quarter = this.getCurrentQuarter(currentDate);
        // const year = currentDate.getFullYear();
        // const period = `${quarter} ${year}`;

        const { quarter, year } = data;
        const period = `${quarter} ${year}`

        try {
            // Get all active employees with their managers
            const employees = await this.prisma.user.findMany({
                where: {
                    status: 'ACTIVE',
                    departments: {
                        some: {}
                    },
                },
                include: {
                    departments: {
                        include: {
                            approver: {
                                where: { role: 'DEPT_MANAGER'}
                            }
                        }
                    }
                }
            });

            const appraisalsToCreate = [];

            for (const employee of employees) {
                // departments is an array; approver inside each department is also an array (due to the `where` in include).
                // Find a department that has at least one approver with role 'DEPT_MANAGER'.
                const deptWithManager = employee.departments.find(dep =>
                    Array.isArray(dep.approver) && dep.approver.length > 0 && dep.approver[0].role === 'DEPT_MANAGER'
                );

                if (!deptWithManager) {
                    this.logger.warn(`No department manager found for user ${employee.email}. Skipping appraisal creation.`);
                    continue;
                }

                const manager = deptWithManager.approver[0];

                // Ensure we don't already have an appraisal for this employee for this quarter/year
                const existing = await this.prisma.appraisal.findFirst({
                    where: {
                        quarter: `${quarter}`,
                        year,
                        appraisedId: employee.id
                    }
                });

                if(existing) continue;

                // Get global KPIs (created by ADMIN) - only approved ones
                const globalCategories = await this.prisma.kpiCategory.findMany({
                    where: { 
                        isGlobal: true,
                        isApproved: true 
                    },
                    include: { objectives: true }
                });

                // Get department-specific KPIs (created by Department Manager) - only approved ones
                const departmentCategories = await this.prisma.kpiCategory.findMany({
                    where: { 
                        departmentId: manager.departmentId,
                        isGlobal: false,
                        isApproved: true
                    },
                    include: { objectives: true }
                });

                // Combine all categories
                const allCategories = [...globalCategories, ...departmentCategories];

                // Only create appraisal if there are categories available
                if (allCategories.length > 0) {
                    appraisalsToCreate.push({
                        quarter: `${quarter}`,
                        year,
                        period: `${quarter} ${year}`,
                        appraiserId: manager.userId,
                        appraisedId: employee.id,
                        status: 'GENERATED',
                        autoGenerated: true,
                        departmentId: manager.departmentId, // Store department for reference
                    });
                } else {
                    this.logger.warn(`No KPI categories found for employee ${employee.email}. Skipping appraisal creation.`);
                }
            }

            // Create appraisals in a transaction
            if(appraisalsToCreate.length > 0) {
                // Create appraisals and capture created records
                const created = await this.prisma.$transaction(
                    appraisalsToCreate.map(data => this.prisma.appraisal.create({ data }))
                );
                this.logger.log(`Successfully created ${created.length} appraisals for period ${period}.`);

                // Initialize KPI data for all generated appraisals using existing categories
                await this.initializeAppraisalData(created);
            } else {
                this.logger.log(`No appraisals to create for this ${period}.`);
            }
        } catch (error) {
            if (error instanceof BadRequestException || 
                error instanceof NotFoundException || 
                error instanceof ConflictException) {
            throw error;
            }
            throw new BadRequestException('Failed to generate quarterly appraisals:' + error.message);
        }
    }

    /////////////////////////////////// HELPER METHODS ///////////////////////////////////

    private getCurrentQuarter(date: Date): number {
        // getMonth returns 0-11 so add 1
        const month = date.getMonth() + 1;
        return Math.ceil(month / 3);
    }

    private async initializeAppraisalData(appraisals: any[]) {
        for (const appraisal of appraisals) {
            try {
                // Get global KPIs for this appraisal
                const globalCategories = await this.prisma.kpiCategory.findMany({
                    where: { 
                        isGlobal: true,
                        // isApproved: true 
                    },
                    include: { objectives: true }
                });

                // Get department-specific KPIs for this appraisal's department
                const departmentCategories = await this.prisma.kpiCategory.findMany({
                    where: { 
                        departmentId: appraisal.departmentId,
                        isGlobal: false,
                        isApproved: true
                    },
                    include: { objectives: true }
                });

                // Combine all categories
                const allCategories = [...globalCategories, ...departmentCategories];

                if (allCategories.length === 0) {
                    this.logger.warn(`No KPI categories found for appraisal ${appraisal.id}. Skipping KPI initialization.`);
                    continue;
                }

                // Create KPI structure with existing categories
                await this.prisma.kpi.create({
                    data: {
                        appraisalId: appraisal.id,
                        categories: {
                            create: allCategories.map(category => ({
                                name: category.name,
                                type: category.type,
                                isGlobal: category.isGlobal,
                                departmentId: category.departmentId,
                                isApproved: true, // Already approved from source
                                // Copy objectives from source category
                                objectives: {
                                    create: category.objectives.map(obj => ({
                                        name: obj.name,
                                        rating: null, // Start with no ratings
                                        comment: null
                                    }))
                                }
                            }))
                        }
                    }
                });

                // Create empty goals and achievements structure
                await this.prisma.goalsAndAchievement.create({
                    data: {
                        appraisalId: appraisal.id,
                        achievements: [],
                        goals: [],
                    },
                });

                // Create empty feedback structure - ensure question is a string (extract if it's an object)
                await this.prisma.feedback.create({
                    data: {
                        appraisalId: appraisal.id,
                        questions: {
                            create: DEFAULT_FEEDBACK_QUESTIONS.map(question => ({
                                question: typeof question === 'string' ? question : question.question, // ensure string value
                                response: null
                            }))
                        }
                    }
                });

                this.logger.log(`Initialized KPI, Goals & Achievement, and Feedback data for appraisal ID: ${appraisal.id}`);
            } catch (error) {
                this.logger.error(`Failed to initialize data for appraisal ${appraisal.id}:`, error);
                // Continue with other appraisals even if one fails
                continue;
            }
        }
    }
}