import {
  BadRequestException,
  Controller,
  Logger,
  Post
} from '@nestjs/common';
// import { KpiCategoryStatus, Role } from '@prisma/client';
import { DEFAULT_FEEDBACK_QUESTIONS } from 'src/constants/kpi-components';
import { PrismaService } from 'src/prisma/prisma.service';
import { bad } from 'src/utils/error.utils';

@Controller('appraisal-scheduler')
export class AppraisalSchedulerController {
  private readonly logger = new Logger(AppraisalSchedulerController.name);

  constructor(private readonly prisma: PrismaService) { }

  // @Post('generate')
  // async generateQuarterlyAppraisals() {
  //   this.logger.log(
  //     'Manually starting quarterly appraisal template generation...',
  //   );

  //   const currentDate = new Date();
  //   // const quarter = this.getCurrentQuarter(currentDate);
  //   const quarter = 2;
  //   const year = currentDate.getFullYear();
  //   const period = `Quarter ${quarter} ${year}`;

  //   // Initialize summary counters
  //   const summary = {
  //     departmentsChecked: 0,
  //     skippedNoManager: 0,
  //     skippedNoKPI: 0,
  //     alreadyExisting: 0,
  //     newTemplates: 0,
  //   };

  //   try {
  //     // Fetch all active departments with their active managers
  //     const employees = await this.prisma.user.findMany({
  //       where: { status: 'ACTIVE', NOT: { userRole: { has: Role.DEPT_MANAGER } } },
  //       include: {
  //         defaultDepartment: {
  //           include: {
  //             approver: {
  //               include: {
  //                 user: true,
  //               },
  //             },
  //           },
  //         },
  //         departments: {
  //           include: {
  //             approver: {
  //               include: {
  //                 user: true,
  //               },
  //             },
  //           },
  //         },
  //       }


  //     });

  //     const appraisalsToCreate = [];

  //     for (const employee of employees) {
  //       summary.departmentsChecked++;

  //       // Ensure department has an active manager
  //       // if (!employee.department.approver || employee.department.approver.length === 0) {
  //       //   this.logger.warn(
  //       //     `No active department manager found for department ${department.name}. Skipping.`,
  //       //   );
  //       //   summary.skippedNoManager++;
  //       //   continue;
  //       // }

  //       const manager = employee.departments.length > 1 ? employee.defaultDepartment.approver.find(a => a.role === Role.DEPT_MANAGER) : employee.departments[0].approver.find(a => a.role === Role.DEPT_MANAGER);

  //       const department = employee.departments.length > 1 ? employee.defaultDepartment : employee.departments[0];

  //       // Check if appraisal template already exists for this quarter/year
  //       const existing = await this.prisma.appraisal.findFirst({
  //         where: {
  //           quarter: `${quarter}`,
  //           year,
  //           appraisedId: employee.id,
  //           isTemplate: true,
  //         },
  //       });

  //       if (existing) {
  //         this.logger.log(
  //           `Appraisal template already exists for employee ${employee.firstName} ${employee.lastName} (${period}). Skipping.`,
  //         );
  //         summary.alreadyExisting++;
  //         continue;
  //       }

  //       // Get approved KPI categories (global + department)
  //       const globalCategories = await this.prisma.kpiCategory.findMany({
  //         where: { isGlobal: true, status: KpiCategoryStatus.APPROVED },
  //         include: { objectives: true },
  //       });

  //       // const departmentCategories = await this.prisma.kpiCategory.findMany({
  //       //   where: {
  //       //     departmentId: department.id,
  //       //     isGlobal: false,
  //       //     status: KpiCategoryStatus.APPROVED,
  //       //   },
  //       //   include: { objectives: true },
  //       // });

  //       // const allCategories = [...globalCategories, ...departmentCategories];
  //       const allCategories = [...globalCategories];

  //       if (allCategories.length === 0) {
  //         this.logger.warn(
  //           `No KPI categories found for employee ${employee.firstName} ${employee.lastName}. Skipping.`,
  //         );
  //         summary.skippedNoKPI++;
  //         continue;
  //       }

  //       // Add to create list
  //       appraisalsToCreate.push({
  //         quarter: `${quarter}`,
  //         year,
  //         period,
  //         appraiserId: manager.userId,
  //         appraisedId: employee.id,
  //         status: 'GENERATED',
  //         autoGenerated: true,
  //         departmentId: department.id,
  //         isTemplate: true,
  //       });
  //     }

  //     // Create appraisal templates in a transaction
  //     if (appraisalsToCreate.length > 0) {
  //       const created = await this.prisma.$transaction(
  //         appraisalsToCreate.map((data) =>
  //           this.prisma.appraisal.create({ data }),
  //         ),
  //       );

  //       summary.newTemplates = created.length;

  //       this.logger.log(
  //         `Successfully created ${created.length} appraisal templates for ${period}.`,
  //       );

  //       // Initialize KPI, goals, and feedback for each template
  //       await this.initializeAppraisalData(created);
  //     } else {
  //       this.logger.log(`No new appraisal templates to create for ${period}.`);
  //     }

  //     // Final return
  //     return {
  //       success: true,
  //       message:
  //         summary.newTemplates > 0
  //           ? `Created ${summary.newTemplates} appraisal templates for ${period}`
  //           : `No new appraisal templates created for ${period}`,
  //       period,
  //       summary,
  //     };
  //   } catch (error) {
  //     this.logger.error(
  //       'Failed to generate quarterly appraisal templates:',
  //       error,
  //     );
  //     throw new BadRequestException(
  //       'Failed to generate quarterly appraisal templates: ' + error.message,
  //     );
  //   }
  // }



  // @Post('generate')
  // async generateQuarterlyAppraisals() {
  //   this.logger.log(
  //     'Manually starting quarterly appraisal template generation...',
  //   );

  //   try {
  //     const orgKpiCategories = await this.prisma.kpiCategory.findMany({
  //       where: {
  //         isGlobal: true,
  //         status: KpiCategoryStatus.APPROVED,
  //       },
  //       include: { objectives: true },
  //     });

  //     const leadershipAssessmentItems = await this.prisma.appraisalLeadership.findMany({});

  //     const returnData = {
  //       success: true,
  //       message: 'Fetched global KPI categories successfully',
  //       cat: orgKpiCategories,
  //       leadership: leadershipAssessmentItems,
  //     };


  //     return { success: true, message: 'Fetched global KPI categories successfully', returnData };
  //   } catch (error) {
  //     bad(error)
  //   }
  // }


  /////////////////////////////////// HELPER METHODS ///////////////////////////////////

  private getCurrentQuarter(date: Date): number {
    const month = date.getMonth() + 1;
    return Math.ceil(month / 3);
  }

  // private async initializeAppraisalData(appraisals: any[]) {
  //   for (const appraisal of appraisals) {
  //     try {
  //       // Get global KPIs for this appraisal
  //       const globalCategories = await this.prisma.kpiCategory.findMany({
  //         where: {
  //           isGlobal: true,
  //           status: KpiCategoryStatus.APPROVED,
  //         },
  //         include: { objectives: true },
  //       });

  //       // Get department-specific KPIs for this appraisal's department
  //       const departmentCategories = await this.prisma.kpiCategory.findMany({
  //         where: {
  //           departmentId: appraisal.departmentId,
  //           isGlobal: false,
  //           status: KpiCategoryStatus.APPROVED,
  //         },
  //         include: { objectives: true },
  //       });

  //       // Combine all categories
  //       const allCategories = [...globalCategories, ...departmentCategories];

  //       if (allCategories.length === 0) {
  //         this.logger.warn(
  //           `No KPI categories found for appraisal template ${appraisal.id}. Skipping KPI initialization.`,
  //         );
  //         continue;
  //       }

  //       // Create KPI structure with existing categories
  //       await this.prisma.kpi.create({
  //         data: {
  //           appraisalId: appraisal.id,
  //           categories: {
  //             connect: allCategories.map((category) => ({ id: category.id })),
  //           },
  //         },
  //       });
  //       // Create empty goals and achievements structure
  //       await this.prisma.goalsAndAchievement.create({
  //         data: {
  //           appraisalId: appraisal.id,
  //           achievements: [],
  //           goals: [],
  //         },
  //       });

  //       // Create empty feedback structure
  //       await this.prisma.feedback.create({
  //         data: {
  //           appraisalId: appraisal.id,
  //           questions: {
  //             create: DEFAULT_FEEDBACK_QUESTIONS.map((question) => ({
  //               question:
  //                 typeof question === 'string' ? question : question.question,
  //               response: null,
  //               order: question.order,
  //             })),
  //           },
  //         },
  //       });

  //       this.logger.log(
  //         `Initialized KPI, Goals & Achievement, and Feedback data for appraisal template ID: ${appraisal.id}`,
  //       );
  //     } catch (error) {
  //       this.logger.error(
  //         `Failed to initialize data for appraisal template ${appraisal.id}:`,
  //         error,
  //       );
  //       continue;
  //     }
  //   }
  // }
}
