version: 0.2

phases:
  install:
    commands:
      # Disable Husky for production build
      - npm pkg delete scripts.prepare
      - npm install -g pnpm@8.15.8
      - pnpm install --ignore-scripts
  build:
    commands:
      - echo Build Started
      - sed -i prisma/schema.prisma -e 's/"native"/"native","rhel-openssl-1.0.x"/g'
      - npx prisma generate
      - pnpm build
artifacts:
  enable-symlinks: yes
  files:
    - .npmrc
    - Procfile
    - package.json
    - pnpm-lock.yaml
    - node_modules/**/*
    - dist/**/*
    - prisma/**/*
    - package.json
cache:
  paths:
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
    - '/root/.cache/**/*'
    - '~/.pnpm-store/**/*'
    - '~/.local/share/pnpm/store'
